//! `tpt-t-cli deny` — emit a `cargo-deny.toml` enforcing the MIT-chain policy
//! (spec §2 / §13). The content mirrors the workspace policy so a scaffolded
//! crate carries the same license audit rules.

/// Exit code on success.
const OK: i32 = 0;
/// Exit code on failure.
const FAIL: i32 = 1;

/// deny subcommand entry point.
pub fn run(args: &[String]) -> i32 {
    let mut out: Option<String> = None;

    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--out" => {
                i += 1;
                if i >= args.len() {
                    eprintln!("error: --out requires a value");
                    return FAIL;
                }
                out = Some(args[i].clone());
            }
            other if other.starts_with("--out=") => {
                out = Some(other["--out=".len()..].to_string());
            }
            other => {
                eprintln!("error: unexpected argument {other:?}");
                return FAIL;
            }
        }
        i += 1;
    }

    let out = out.unwrap_or_else(|| "cargo-deny.toml".into());
    match std::fs::write(&out, DENY_TOML) {
        Ok(()) => {
            println!("wrote cargo-deny config to {out}");
            OK
        }
        Err(e) => {
            eprintln!("error: cannot write {out}: {e}");
            FAIL
        }
    }
}

/// The MIT-chain `cargo-deny.toml` template (generated by `tpt-t-cli deny`).
const DENY_TOML: &str = "\
# cargo-deny configuration — the \"MIT Chain\" policy (spec §2)
#
# Generated by `tpt-t-cli deny`. tpt-teleop keeps its dependency tree free of
# Apache-only patent liabilities:
#   * Allowed: MIT, BSD-2/3-Clause, ISC, Zlib, MPL-2.0.
#   * Dual MIT OR Apache-2.0 crates are permitted, but resolved strictly under
#     MIT via the [[licenses.clarify]] overrides below.
#   * Strictly Apache-2.0-only crates are banned outright.

[graph]
all-features = true
targets = [
    { triple = \"x86_64-unknown-linux-gnu\" },
    { triple = \"aarch64-apple-darwin\" },
    { triple = \"x86_64-pc-windows-msvc\" },
]

[licenses]
version = 2
allow = [
    \"MIT\",
    \"BSD-2-Clause\",
    \"BSD-3-Clause\",
    \"ISC\",
    \"Zlib\",
    \"MPL-2.0\",
    \"Unicode-DFS-2016\",
    \"Unicode-3.0\",
]
deny = [ \"Apache-2.0\" ]
confidence-threshold = 0.93

[[licenses.clarify]]
name = \"rkyv\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"rkyv_derive\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"bytecheck\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"bytecheck_derive\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"ptr_meta\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"rend\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"rancor\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"proc-macro2\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"quote\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"syn\"
expression = \"MIT\"

[[licenses.clarify]]
name = \"unicode-ident\"
expression = \"MIT\"

[bans]
multiple-versions = \"warn\"
wildcards = \"deny\"
highlight = \"all\"

[sources]
unknown-registry = \"deny\"
unknown-git = \"deny\"
allow-registry = [\"https://github.com/rust-lang/crates.io-index\"]

[advisories]
version = 2
yanked = \"warn\"
";
