//! `tpt-t-cli profile` — emit a CPU core-pinning profile (`core-profile.txt`)
//! assigning latency-critical roles to dedicated cores (spec §13 / §3.1).
//!
//! Roles follow the canonical order Video, Control, Network, Input, Media,
//! Storage; any remaining cores are handed to Spare.

use tpt_t_core::profile::{CoreProfile, Role};

/// Exit code on success.
const OK: i32 = 0;
/// Exit code on failure.
const FAIL: i32 = 1;

/// profile subcommand entry point.
pub fn run(args: &[String]) -> i32 {
    let mut cores: Option<usize> = None;
    let mut out: Option<String> = None;

    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--cores" => {
                i += 1;
                if i >= args.len() {
                    eprintln!("error: --cores requires a value");
                    return FAIL;
                }
                match args[i].parse::<usize>() {
                    Ok(n) => cores = Some(n),
                    Err(e) => {
                        eprintln!("error: --cores: {e}");
                        return FAIL;
                    }
                }
            }
            "--out" => {
                i += 1;
                if i >= args.len() {
                    eprintln!("error: --out requires a value");
                    return FAIL;
                }
                out = Some(args[i].clone());
            }
            other if other.starts_with("--cores=") => match other["--cores=".len()..].parse() {
                Ok(n) => cores = Some(n),
                Err(e) => {
                    eprintln!("error: --cores: {e}");
                    return FAIL;
                }
            },
            other if other.starts_with("--out=") => {
                out = Some(other["--out=".len()..].to_string());
            }
            other => {
                eprintln!("error: unexpected argument {other:?}");
                return FAIL;
            }
        }
        i += 1;
    }

    let cores = cores.unwrap_or_else(|| tpt_t_core::affinity::core_count().max(1));
    let text = default_profile_text(cores);

    // Validate the generated profile against the machine it targets.
    match CoreProfile::parse(&text) {
        Ok(p) => {
            if let Err(e) = p.validate(cores) {
                eprintln!("warning: generated profile is invalid: {e}");
            }
        }
        Err(e) => {
            eprintln!("warning: generated profile is invalid: {e}");
        }
    }

    match &out {
        Some(path) => match std::fs::write(path, &text) {
            Ok(()) => {
                println!("wrote core profile to {path} ({cores} cores)");
                OK
            }
            Err(e) => {
                eprintln!("error: cannot write {path}: {e}");
                FAIL
            }
        },
        None => {
            println!("{text}");
            OK
        }
    }
}

/// Builds a default `core-profile.txt` body for `cores` available cores.
pub fn default_profile_text(cores: usize) -> String {
    let cores = cores.max(1);
    let mut s = String::new();
    s.push_str("# tpt-teleop core profile (generated by tpt-t-cli profile)\n");
    s.push_str(&format!("# cores available: {cores}\n"));

    for (r, role) in Role::ALL.iter().enumerate() {
        if r >= cores {
            break;
        }
        if *role == Role::Spare {
            continue; // spare handled below so its cores form a tail range
        }
        s.push_str(&format!("{} = {r}\n", role.key()));
    }

    if cores > Role::ALL.len() {
        let spec = format!("6-{}", cores - 1);
        s.push_str(&format!("{} = {spec}\n", Role::Spare.key()));
    }

    s
}
